/********************************************************************
 * COPYRIGHT -- General Atomics
 ********************************************************************
 * Library: 
 * File: EventMap.hpp
 * Author: J. Sheeron (x2315)
 * Created: September 20, 2014
  *******************************************************************
 * Function:  
 *
 * Libraries used:
 *******************************************************************/
#pragma once

#ifndef GA_ScsData_EventMap_H_
#define GA_ScsData_EventMap_H_

// standard c/c++ libraries

// GA headers
#include "gaScsDataConstants.hpp"
#include "CoilMap.hpp"

namespace gaScsData {

class EventMap : private boost::noncopyable { 

public:
  // typedefs and enums

    // Event map definition
      // comprised of an angle key, and tuple holding the info for the event
      // The typle is comprised of the EventId (long), Logic Trace (string for debugging)
      typedef boost::tuple<long, std::string> EventDataTyp;
      typedef std::pair<double, EventDataTyp> EventValueTyp; // multimap value type -- key float value and the event data. Used for multimap insert
      // the event map is implemented as a multimap of <angle, eventData>. There may be one or more events at a given angle, so a multimap (instead of map) is used.
      typedef boost::container::multimap<double, EventDataTyp> EventMapTyp;
      // define iterators to allow iterating over the event map
      typedef EventMapTyp::iterator em_iter;
      typedef EventMapTyp::const_iterator em_const_iter;

 
      // The event ids need to match the event class table in the database.
      // This code does not generate instances of all these event ids.
      // In particular, dynamic events are not generated by this code.
      // User stop, alarm stop, burr detect, tape splice, and inspect fiducial are not generated for example.
      enum EventIds { EID_USER_STOP = 1000,
                      EID_ALARM_STOP = 1001,
                      EID_CAL_TOOL = 1002,
                      EID_INSTALL_COIL = 1003,
                      EID_LOAD_FIRST_HEX = 1004,
                      EID_INSTALL_RIA_AWH = 1005,
                      EID_INSPECT_BURRS = 1006,
                      EID_LAYER_INCREMENT = 1007,
                      EID_CONSOLIDATE_ODD = 1008, // Consolidate odd layer turns
                      EID_TEACH_FIDUCIAL = 1009,
                      EID_HQP_LOAD = 1010,
                      EID_TAPE_SPLICE1 = 1011,  // awh head 1
                      EID_TAPE_SPLICE2 = 1012,  // awh head 2
                      EID_TAPE_SPLICE3 = 1013,  // awh head 3
                      EID_INSPECT_FIDUCIAL_MARK = 1014,
                      EID_REMOVE_PLOW = 1015,
                      EID_HE_PIPE_INSULATION = 1016,
                      EID_END_ODD_LAYER = 1017,
                      EID_OPEN_LANDING_ROLLER = 1018, // avoid helium pipe
                      EID_END_EVEN_LAYER = 1019,
                      EID_LAYER_COMPRESSION = 1020,
                      EID_TURN_MEASUREMENT = 1021,
                      EID_MOVE_ECHAIN = 1022,  // Move FO E-chain and increment layer
                      EID_LONG_LEAD_ENDGAME = 1023 }; // long lead end game and RIA disassembly


     // constants

    // ctors and dtor
    EventMap();
    ~EventMap();

  // accessors

  // public methods
    long GenerateEventMapTable();

  private:
    // helper functions

    // event related functions
      // look at the coil map and see when an event should be created.
      // true - conditions are correct for making an event instance, false -- they are not.
      bool isEventLayerIncrement(CoilMap::cm_cit cit) const;
      bool isEventEndEvenLayer(CoilMap::cm_cit cit) const;
      bool isEventConsolidateOdd(CoilMap::cm_cit cit) const;
      bool isEventHqpLoad(CoilMap::cm_cit cit) const;
      bool isEventTeachFiducial(CoilMap::cm_cit cit) const;
      bool isEventRemovePlow(CoilMap::cm_cit cit) const;
      bool isEventHePipeInsulation(CoilMap::cm_cit cit) const;
      bool isEventOpenLandingRoller(CoilMap::cm_cit cit) const;
      bool isEventEndOddLayer(CoilMap::cm_cit cit) const;
      bool isEventLayerCompression(CoilMap::cm_cit cit) const;
      bool isEventTurnMeasurement(CoilMap::cm_cit cit) const;
      bool isEventMoveEChain(CoilMap::cm_cit cit) const;
      bool isEventLeadEndgame(CoilMap::cm_cit cit) const;

      // add the specified event ID to the event map at the specified angle
      void AddEventToMap(double angle, long eventId, std::string logicTrace = "");
      // iterates over the operational range of angles and determies which events happen at which angles
      void MapEventInstances();

      // DB related functions
      long DbConnect();
      // insert a row at the angle. Use the passed in event id. Each call will connect do the insert, and disconnect from the db.
      long InsertIntoDb(double angle, long eventId, const std::string &sprocName, const std::string& trace = "none");
      long InsertIntoDb(const std::string &sprocName); // Iterate thru event map and insert a row for each map entry. Each call will connect, insert all the events in the event map, and then disconnect.
      long DbDisconnect();

    // member variables

       // coil map
      CoilMap coilMap_;

      // Event properties
//      EventDataTyp eventData_;

      // Event map
      EventMapTyp eventMap_;

      // Event value type
      EventValueTyp eventValue_;

      // specify server and db string
      std::string serverText_;
      // error text
      std::string errorText_;
      
      // db objects
      SAConnection dbConnection_; // create connection object
      SACommand dbCommand_; // create connection object
};

} //namespace gaScsData
#endif // GA_ScsData_EventMap_H_

